"""Initial revision

Revision ID: 279ee92061a6
Revises: 
Create Date: 2024-11-05 15:48:58.628517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279ee92061a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(),primary_key=True, nullable=False, autoincrement=True),
    sa.Column('match_date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('guest', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
