"""Initial revision

Revision ID: 511c2b2c1bc9
Revises:
Create Date: 2024-11-05 15:48:58.628517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import foreign

# revision identifiers, used by Alembic.
revision: str = '511c2b2c1bc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), primary_key=True, nullable=False, autoincrement=True),
    sa.Column('match_date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('scores', sa.String(), nullable=False),
    sa.Column('owner', sa.Integer(), sa.ForeignKey('teams.id'), nullable=False),
    sa.Column('guest', sa.Integer(), sa.ForeignKey('teams.id'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=False)
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_owner_fkey')
    op.execute('ALTER TABLE matches DROP CONSTRAINT IF EXISTS matches_guest_fkey')

    op.execute('TRUNCATE TABLE matches RESTART IDENTITY CASCADE')
    op.drop_table('matches')
    # ### end Alembic commands ###
